# permissions for end users to view podmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmonitor-viewer-role
rules:
- apiGroups:
  - lsalab.nthu.lsalab.nthu
  resources:
  - podmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lsalab.nthu.lsalab.nthu
  resources:
  - podmonitors/status
  verbs:
  - get
