apiVersion: v1
kind: ServiceAccount
metadata:
  name: podmonitor-operator
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podmonitor-operator
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["lsalab.nthu"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podmonitor-operator
subjects:
- kind: ServiceAccount
  name: podmonitor-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: podmonitor-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: podmonitor-operator
  namespace: kube-system
  labels:
    app: podmonitor-operator
spec:
  serviceAccountName: podmonitor-operator
  containers:
  - name: podmonitor-operator
    image: riyazhu/podmonitor-operator:latest
